// ─────────────────────────────────────────────────────────
// SVG ORNAMENT LIBRARY
// Inline SVG path data for decorative chapter ornaments
// ─────────────────────────────────────────────────────────

export const svgOrnaments = {
  // Classic floral flourish
  floralFlourish: `<svg viewBox="0 0 200 30" xmlns="http://www.w3.org/2000/svg"><path d="M100 15 C90 5, 70 0, 50 5 C30 10, 20 15, 10 15 C20 15, 30 20, 50 25 C70 30, 90 25, 100 15Z" fill="currentColor" opacity="0.6"/><path d="M100 15 C110 5, 130 0, 150 5 C170 10, 180 15, 190 15 C180 15, 170 20, 150 25 C130 30, 110 25, 100 15Z" fill="currentColor" opacity="0.6"/><circle cx="100" cy="15" r="3" fill="currentColor"/></svg>`,

  // Elegant swirl divider
  elegantSwirl: `<svg viewBox="0 0 200 24" xmlns="http://www.w3.org/2000/svg"><path d="M20 12 Q40 2, 60 12 T100 12 T140 12 T180 12" fill="none" stroke="currentColor" stroke-width="1.5" opacity="0.5"/><circle cx="100" cy="12" r="2.5" fill="currentColor" opacity="0.7"/><circle cx="80" cy="12" r="1.5" fill="currentColor" opacity="0.4"/><circle cx="120" cy="12" r="1.5" fill="currentColor" opacity="0.4"/></svg>`,

  // Diamond geometric
  diamondGeometric: `<svg viewBox="0 0 200 20" xmlns="http://www.w3.org/2000/svg"><line x1="20" y1="10" x2="85" y2="10" stroke="currentColor" stroke-width="0.75" opacity="0.4"/><polygon points="100,2 108,10 100,18 92,10" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.7"/><circle cx="100" cy="10" r="2" fill="currentColor" opacity="0.5"/><line x1="115" y1="10" x2="180" y2="10" stroke="currentColor" stroke-width="0.75" opacity="0.4"/></svg>`,

  // Celtic knot
  celticKnot: `<svg viewBox="0 0 200 30" xmlns="http://www.w3.org/2000/svg"><path d="M80 15 C80 5, 90 2, 100 8 C110 2, 120 5, 120 15 C120 25, 110 28, 100 22 C90 28, 80 25, 80 15Z" fill="none" stroke="currentColor" stroke-width="1.5" opacity="0.6"/><line x1="20" y1="15" x2="78" y2="15" stroke="currentColor" stroke-width="0.75" opacity="0.3"/><line x1="122" y1="15" x2="180" y2="15" stroke="currentColor" stroke-width="0.75" opacity="0.3"/></svg>`,

  // Gothic cross
  gothicCross: `<svg viewBox="0 0 200 30" xmlns="http://www.w3.org/2000/svg"><line x1="20" y1="15" x2="88" y2="15" stroke="currentColor" stroke-width="0.75" opacity="0.3"/><rect x="95" y="5" width="10" height="20" rx="1" fill="currentColor" opacity="0.5"/><rect x="90" y="10" width="20" height="10" rx="1" fill="currentColor" opacity="0.5"/><line x1="112" y1="15" x2="180" y2="15" stroke="currentColor" stroke-width="0.75" opacity="0.3"/></svg>`,

  // Celestial stars and moon
  celestialStars: `<svg viewBox="0 0 200 24" xmlns="http://www.w3.org/2000/svg"><path d="M90 12 A8 8 0 1 1 90 11.99" fill="none" stroke="currentColor" stroke-width="1" opacity="0.5"/><path d="M93 8 A6 6 0 0 0 93 16" fill="currentColor" opacity="0.4"/><polygon points="115,6 116.5,10 121,10 117.5,13 119,17 115,14.5 111,17 112.5,13 109,10 113.5,10" fill="currentColor" opacity="0.6" transform="scale(0.7) translate(50, 5)"/><polygon points="140,8 141,10.5 143.5,10.5 141.5,12 142.5,14.5 140,13 137.5,14.5 138.5,12 136.5,10.5 139,10.5" fill="currentColor" opacity="0.4"/><line x1="20" y1="12" x2="80" y2="12" stroke="currentColor" stroke-width="0.5" opacity="0.25"/><line x1="155" y1="12" x2="180" y2="12" stroke="currentColor" stroke-width="0.5" opacity="0.25"/></svg>`,

  // Leaf / nature
  leafNature: `<svg viewBox="0 0 200 24" xmlns="http://www.w3.org/2000/svg"><path d="M90 16 Q95 4, 100 12 Q105 4, 110 16" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.5"/><path d="M96 14 Q100 6, 104 14" fill="currentColor" opacity="0.3"/><line x1="100" y1="12" x2="100" y2="20" stroke="currentColor" stroke-width="1" opacity="0.4"/><line x1="30" y1="16" x2="88" y2="16" stroke="currentColor" stroke-width="0.5" opacity="0.25"/><line x1="112" y1="16" x2="170" y2="16" stroke="currentColor" stroke-width="0.5" opacity="0.25"/></svg>`,

  // Art deco geometric
  artDecoGeometric: `<svg viewBox="0 0 200 24" xmlns="http://www.w3.org/2000/svg"><line x1="30" y1="12" x2="80" y2="12" stroke="currentColor" stroke-width="1.5" opacity="0.5"/><rect x="84" y="6" width="32" height="12" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.5"/><line x1="90" y1="6" x2="90" y2="18" stroke="currentColor" stroke-width="0.75" opacity="0.3"/><line x1="100" y1="6" x2="100" y2="18" stroke="currentColor" stroke-width="0.75" opacity="0.3"/><line x1="110" y1="6" x2="110" y2="18" stroke="currentColor" stroke-width="0.75" opacity="0.3"/><line x1="120" y1="12" x2="170" y2="12" stroke="currentColor" stroke-width="1.5" opacity="0.5"/></svg>`,

  // Vintage typewriter
  vintageTypewriter: `<svg viewBox="0 0 200 16" xmlns="http://www.w3.org/2000/svg"><line x1="30" y1="8" x2="80" y2="8" stroke="currentColor" stroke-width="1" opacity="0.4"/><circle cx="90" cy="8" r="2" fill="currentColor" opacity="0.5"/><circle cx="100" cy="8" r="3" fill="currentColor" opacity="0.6"/><circle cx="110" cy="8" r="2" fill="currentColor" opacity="0.5"/><line x1="120" y1="8" x2="170" y2="8" stroke="currentColor" stroke-width="1" opacity="0.4"/></svg>`,

  // Sword / fantasy
  swordFantasy: `<svg viewBox="0 0 200 30" xmlns="http://www.w3.org/2000/svg"><line x1="60" y1="15" x2="140" y2="15" stroke="currentColor" stroke-width="1.5" opacity="0.5"/><polygon points="140,15 148,12 148,18" fill="currentColor" opacity="0.6"/><rect x="56" y="11" width="8" height="8" rx="1" fill="currentColor" opacity="0.5"/><line x1="50" y1="15" x2="56" y2="15" stroke="currentColor" stroke-width="3" opacity="0.4"/></svg>`,

  // Rose / romance
  roseRomance: `<svg viewBox="0 0 200 30" xmlns="http://www.w3.org/2000/svg"><circle cx="100" cy="13" r="5" fill="currentColor" opacity="0.25"/><circle cx="96" cy="11" r="4" fill="currentColor" opacity="0.2"/><circle cx="104" cy="11" r="4" fill="currentColor" opacity="0.2"/><circle cx="100" cy="8" r="3.5" fill="currentColor" opacity="0.3"/><path d="M92 18 Q96 22, 100 24 Q104 22, 108 18" fill="none" stroke="currentColor" stroke-width="0.8" opacity="0.4"/><line x1="25" y1="15" x2="85" y2="15" stroke="currentColor" stroke-width="0.5" opacity="0.25"/><line x1="115" y1="15" x2="175" y2="15" stroke="currentColor" stroke-width="0.5" opacity="0.25"/></svg>`,

  // Skull / horror
  skullHorror: `<svg viewBox="0 0 200 30" xmlns="http://www.w3.org/2000/svg"><ellipse cx="100" cy="12" rx="8" ry="9" fill="currentColor" opacity="0.25"/><ellipse cx="96" cy="10" rx="2.5" ry="2" fill="currentColor" opacity="0.5"/><ellipse cx="104" cy="10" rx="2.5" ry="2" fill="currentColor" opacity="0.5"/><path d="M96 16 L98 14 L100 16 L102 14 L104 16" fill="none" stroke="currentColor" stroke-width="0.8" opacity="0.5"/><line x1="20" y1="15" x2="85" y2="15" stroke="currentColor" stroke-width="0.75" opacity="0.3"/><line x1="115" y1="15" x2="180" y2="15" stroke="currentColor" stroke-width="0.75" opacity="0.3"/></svg>`,

  // Key / mystery
  keyMystery: `<svg viewBox="0 0 200 24" xmlns="http://www.w3.org/2000/svg"><circle cx="85" cy="12" r="6" fill="none" stroke="currentColor" stroke-width="1.2" opacity="0.5"/><circle cx="85" cy="12" r="2.5" fill="currentColor" opacity="0.3"/><line x1="91" y1="12" x2="130" y2="12" stroke="currentColor" stroke-width="1.5" opacity="0.5"/><line x1="120" y1="12" x2="120" y2="17" stroke="currentColor" stroke-width="1.2" opacity="0.5"/><line x1="128" y1="12" x2="128" y2="17" stroke="currentColor" stroke-width="1.2" opacity="0.5"/></svg>`,

  // Star burst
  starBurst: `<svg viewBox="0 0 200 24" xmlns="http://www.w3.org/2000/svg"><polygon points="100,3 103,9 110,9 105,13 107,20 100,16 93,20 95,13 90,9 97,9" fill="currentColor" opacity="0.5"/><line x1="30" y1="12" x2="86" y2="12" stroke="currentColor" stroke-width="0.5" opacity="0.25"/><line x1="114" y1="12" x2="170" y2="12" stroke="currentColor" stroke-width="0.5" opacity="0.25"/></svg>`,

  // Ocean wave
  oceanWave: `<svg viewBox="0 0 200 20" xmlns="http://www.w3.org/2000/svg"><path d="M20 10 Q35 4, 50 10 T80 10 T110 10 T140 10 T170 10 T200 10" fill="none" stroke="currentColor" stroke-width="1" opacity="0.4"/><path d="M10 14 Q25 8, 40 14 T70 14 T100 14 T130 14 T160 14 T190 14" fill="none" stroke="currentColor" stroke-width="0.75" opacity="0.25"/></svg>`,

  // Simple thin rule
  thinRule: `<svg viewBox="0 0 200 8" xmlns="http://www.w3.org/2000/svg"><line x1="40" y1="4" x2="160" y2="4" stroke="currentColor" stroke-width="0.75" opacity="0.35"/></svg>`,

  // Double rule
  doubleRule: `<svg viewBox="0 0 200 12" xmlns="http://www.w3.org/2000/svg"><line x1="40" y1="4" x2="160" y2="4" stroke="currentColor" stroke-width="0.75" opacity="0.35"/><line x1="40" y1="9" x2="160" y2="9" stroke="currentColor" stroke-width="0.75" opacity="0.35"/></svg>`,

  // Ornate frame corners (for decorative borders)
  ornateCorner: `<svg viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg"><path d="M5 35 L5 15 Q5 5, 15 5 L35 5" fill="none" stroke="currentColor" stroke-width="1" opacity="0.35"/><path d="M8 32 L8 18 Q8 8, 18 8 L32 8" fill="none" stroke="currentColor" stroke-width="0.5" opacity="0.2"/><circle cx="5" cy="35" r="1.5" fill="currentColor" opacity="0.3"/></svg>`,
};

// Helper to dynamically convert an integer to English words
function convertNumberToWords(num) {
  if (num === 0) return 'Zero';
  const ones = [
    '', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 
    'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'
  ];
  const tens = [
    '', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'
  ];

  function convert(n) {
    if (n < 20) return ones[n];
    if (n < 100) return tens[Math.floor(n / 10)] + (n % 10 !== 0 ? '-' + ones[n % 10] : '');
    if (n < 1000) return ones[Math.floor(n / 100)] + ' Hundred' + (n % 100 !== 0 ? ' and ' + convert(n % 100) : '');
    return ones[Math.floor(n / 1000)] + ' Thousand' + (n % 1000 !== 0 ? ' ' + convert(n % 1000) : '');
  }

  return convert(num);
}

// Helper to dynamically convert an integer to Roman numerals
function convertNumberToRoman(num) {
  if (num <= 0) return '';
  const lookup = [
    ['M', 1000], ['CM', 900], ['D', 500], ['CD', 400], 
    ['C', 100], ['XC', 90], ['L', 50], ['XL', 40], 
    ['X', 10], ['IX', 9], ['V', 5], ['IV', 4], ['I', 1]
  ];
  let roman = '';
  let val = num;
  for (const [letter, value] of lookup) {
    while (val >= value) {
      roman += letter;
      val -= value;
    }
  }
  return roman;
}

/**
 * Generate the chapter number label text based on the numbering style and chapter index.
 * @param {number} chapterIndex - 1-based index of the chapter
 * @param {string} style - 'word-upper' | 'word-capitalize' | 'number' | 'roman-upper' | 'none'
 * @returns {string} Formatted chapter label, e.g. "CHAPTER ONE"
 */
export function getChapterLabel(chapterIndex, style = 'word-upper') {
  if (style === 'none') return '';
  const num = Math.max(1, chapterIndex);
  switch (style) {
    case 'word-upper':
      return `CHAPTER ${convertNumberToWords(num).toUpperCase()}`;
    case 'word-capitalize':
      return `Chapter ${convertNumberToWords(num)}`;
    case 'number':
      return `Chapter ${num}`;
    case 'roman-upper':
      return `CHAPTER ${convertNumberToRoman(num)}`;
    default:
      return `CHAPTER ${convertNumberToWords(num).toUpperCase()}`;
  }
}

// ─────────────────────────────────────────────────────────
// THEME PRESETS
// ─────────────────────────────────────────────────────────

export const themes = [
  {
    id: 'classic-novel',
    name: 'Classic Novel',
    description: 'Traditional literature styling with old-style serif typography and elegant spacing.',
    category: 'Traditional',
    bodyFont: "'EB Garamond', Garamond, serif",
    headingFont: "'EB Garamond', Garamond, serif",
    fontSize: '15.5px',
    lineHeight: '1.5',
    paragraphSpacing: '0',
    indentation: '1.5em',
    dividerSymbol: '❦',
    chapterSpacing: '60px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.75em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '1.9em',
      titleWeight: 500,
      titleLetterSpacing: '0.5px',
      topMargin: '22%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '18px',
      gapBetweenOrnamentAndBody: '28px',
      ornamentType: 'symbol',
      ornamentSvgKey: null,
      decorativeBorder: false,
    }
  },
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean, contemporary aesthetic using modern sans-serif headers and open spacing.',
    category: 'Contemporary',
    bodyFont: "'Lora', Georgia, serif",
    headingFont: "'Inter', sans-serif",
    fontSize: '14.5px',
    lineHeight: '1.6',
    paragraphSpacing: '6px',
    indentation: '0',
    dividerSymbol: '—',
    chapterSpacing: '40px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: false,
    justify: false,
    dividerStyle: 'line',
    chapterOpening: {
      layout: 'left-aligned',
      numberSize: '0.7em',
      numberLetterSpacing: '4px',
      numberWeight: 600,
      numberVariant: 'normal',
      titleSize: '2.2em',
      titleWeight: 300,
      titleLetterSpacing: '0px',
      topMargin: '18%',
      gapBetweenNumberAndTitle: '6px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '24px',
      ornamentType: 'svg',
      ornamentSvgKey: 'thinRule',
      decorativeBorder: false,
    }
  },
  {
    id: 'elegant-serif',
    name: 'Elegant Serif',
    description: 'High-end layout featuring Cormorant Garamond for sophisticated, clean text flows.',
    category: 'Traditional',
    bodyFont: "'Cormorant Garamond', serif",
    headingFont: "'Cormorant Garamond', serif",
    fontSize: '16px',
    lineHeight: '1.55',
    paragraphSpacing: '0',
    indentation: '1.4em',
    dividerSymbol: '✧',
    chapterSpacing: '50px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.8em',
      numberLetterSpacing: '4px',
      numberWeight: 300,
      numberVariant: 'all-small-caps',
      titleSize: '2em',
      titleWeight: 400,
      titleLetterSpacing: '1px',
      topMargin: '24%',
      gapBetweenNumberAndTitle: '8px',
      gapBetweenTitleAndOrnament: '16px',
      gapBetweenOrnamentAndBody: '26px',
      ornamentType: 'svg',
      ornamentSvgKey: 'elegantSwirl',
      decorativeBorder: false,
    }
  },
  {
    id: 'literary-fiction',
    name: 'Literary Fiction',
    description: 'High-end publishing style optimized for contemporary award-winning fiction.',
    category: 'Traditional',
    bodyFont: "'Lora', Georgia, serif",
    headingFont: "'Playfair Display', serif",
    fontSize: '15px',
    lineHeight: '1.5',
    paragraphSpacing: '0',
    indentation: '1.5em',
    dividerSymbol: '◆',
    chapterSpacing: '55px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: false,
    justify: true,
    dividerStyle: 'dots',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.7em',
      numberLetterSpacing: '5px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '1.8em',
      titleWeight: 600,
      titleLetterSpacing: '0.5px',
      topMargin: '20%',
      gapBetweenNumberAndTitle: '12px',
      gapBetweenTitleAndOrnament: '16px',
      gapBetweenOrnamentAndBody: '24px',
      ornamentType: 'svg',
      ornamentSvgKey: 'diamondGeometric',
      decorativeBorder: false,
    }
  },
  {
    id: 'cozy-romance',
    name: 'Cozy Romance',
    description: 'Warm and friendly text layout with rounded feel and comfortable line breaks.',
    category: 'Romance',
    bodyFont: "'Lora', serif",
    headingFont: "'Rochester', cursive",
    fontSize: '15px',
    lineHeight: '1.6',
    paragraphSpacing: '0',
    indentation: '1.4em',
    dividerSymbol: '✿ ❀ ✿',
    chapterSpacing: '45px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: false,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.7em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '2.2em',
      titleWeight: 400,
      titleLetterSpacing: '0px',
      topMargin: '20%',
      gapBetweenNumberAndTitle: '6px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '22px',
      ornamentType: 'svg',
      ornamentSvgKey: 'roseRomance',
      decorativeBorder: false,
    }
  },
  {
    id: 'epic-fantasy',
    name: 'Epic Fantasy',
    description: 'Calligraphic serif headings and heavy drop caps inspired by classical legends.',
    category: 'Fantasy',
    bodyFont: "'EB Garamond', Garamond, serif",
    headingFont: "'Cinzel', serif",
    fontSize: '15px',
    lineHeight: '1.5',
    paragraphSpacing: '0',
    indentation: '1.75em',
    dividerSymbol: '✦ ✧ ✦',
    chapterSpacing: '80px',
    firstParagraphStyle: 'uppercase',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.85em',
      numberLetterSpacing: '5px',
      numberWeight: 700,
      numberVariant: 'normal',
      titleSize: '2em',
      titleWeight: 600,
      titleLetterSpacing: '2px',
      topMargin: '26%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '18px',
      gapBetweenOrnamentAndBody: '30px',
      ornamentType: 'svg',
      ornamentSvgKey: 'swordFantasy',
      decorativeBorder: true,
    }
  },
  {
    id: 'dark-fantasy',
    name: 'Dark Fantasy',
    description: 'Moody typography paired with bold medieval accents and tight spacing.',
    category: 'Fantasy',
    bodyFont: "'Spectral', serif",
    headingFont: "'Cinzel', serif",
    fontSize: '14.5px',
    lineHeight: '1.45',
    paragraphSpacing: '0',
    indentation: '1.6em',
    dividerSymbol: '✥',
    chapterSpacing: '75px',
    firstParagraphStyle: 'uppercase',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.8em',
      numberLetterSpacing: '4px',
      numberWeight: 700,
      numberVariant: 'normal',
      titleSize: '1.9em',
      titleWeight: 600,
      titleLetterSpacing: '1.5px',
      topMargin: '24%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '16px',
      gapBetweenOrnamentAndBody: '28px',
      ornamentType: 'svg',
      ornamentSvgKey: 'gothicCross',
      decorativeBorder: true,
    }
  },
  {
    id: 'gothic',
    name: 'Gothic',
    description: 'Dramatic headers with dense text layout, evoking mystery and shadows.',
    category: 'Dark',
    bodyFont: "'IM Fell English', Georgia, serif",
    headingFont: "'Cinzel', serif",
    fontSize: '15.5px',
    lineHeight: '1.5',
    paragraphSpacing: '0',
    indentation: '1.6em',
    dividerSymbol: '☠',
    chapterSpacing: '75px',
    firstParagraphStyle: 'uppercase',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.8em',
      numberLetterSpacing: '5px',
      numberWeight: 700,
      numberVariant: 'normal',
      titleSize: '2em',
      titleWeight: 600,
      titleLetterSpacing: '2px',
      topMargin: '25%',
      gapBetweenNumberAndTitle: '12px',
      gapBetweenTitleAndOrnament: '18px',
      gapBetweenOrnamentAndBody: '28px',
      ornamentType: 'svg',
      ornamentSvgKey: 'gothicCross',
      decorativeBorder: true,
    }
  },
  {
    id: 'dark-academia',
    name: 'Dark Academia',
    description: 'Moody, dense formatting with classic structure and deep intellectual tone.',
    category: 'Dark',
    bodyFont: "'EB Garamond', serif",
    headingFont: "'Playfair Display', serif",
    fontSize: '15px',
    lineHeight: '1.45',
    paragraphSpacing: '0',
    indentation: '1.6em',
    dividerSymbol: '✒',
    chapterSpacing: '65px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.7em',
      numberLetterSpacing: '4px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '1.8em',
      titleWeight: 700,
      titleLetterSpacing: '0.5px',
      topMargin: '22%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '24px',
      ornamentType: 'svg',
      ornamentSvgKey: 'doubleRule',
      decorativeBorder: false,
    }
  },
  {
    id: 'historical',
    name: 'Historical',
    description: 'Authentic 19th-century printing style using classic Garamond serifs.',
    category: 'Traditional',
    bodyFont: "'EB Garamond', Garamond, serif",
    headingFont: "'IM Fell English', serif",
    fontSize: '16px',
    lineHeight: '1.45',
    paragraphSpacing: '0',
    indentation: '1.8em',
    dividerSymbol: '✽',
    chapterSpacing: '70px',
    firstParagraphStyle: 'uppercase',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.75em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '1.9em',
      titleWeight: 400,
      titleLetterSpacing: '1px',
      topMargin: '24%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '16px',
      gapBetweenOrnamentAndBody: '26px',
      ornamentType: 'svg',
      ornamentSvgKey: 'floralFlourish',
      decorativeBorder: false,
    }
  },
  {
    id: 'regency',
    name: 'Regency',
    description: 'Soft script headings, wide margins, and dainty ornaments suited for society tales.',
    category: 'Romance',
    bodyFont: "'Cormorant Garamond', serif",
    headingFont: "'Rochester', cursive",
    fontSize: '15px',
    lineHeight: '1.6',
    paragraphSpacing: '0',
    indentation: '1.5em',
    dividerSymbol: '❦ ❧',
    chapterSpacing: '60px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.7em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '2.4em',
      titleWeight: 400,
      titleLetterSpacing: '0px',
      topMargin: '22%',
      gapBetweenNumberAndTitle: '6px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '22px',
      ornamentType: 'svg',
      ornamentSvgKey: 'elegantSwirl',
      decorativeBorder: false,
    }
  },
  {
    id: 'victorian',
    name: 'Victorian',
    description: 'Ornate headers, heavy leading, and elaborate calligraphic dividers.',
    category: 'Traditional',
    bodyFont: "'Alice', Georgia, serif",
    headingFont: "'Playfair Display', serif",
    fontSize: '15px',
    lineHeight: '1.55',
    paragraphSpacing: '0',
    indentation: '1.6em',
    dividerSymbol: '❧ ❦ ❧',
    chapterSpacing: '70px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.75em',
      numberLetterSpacing: '4px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '2em',
      titleWeight: 600,
      titleLetterSpacing: '1px',
      topMargin: '24%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '18px',
      gapBetweenOrnamentAndBody: '28px',
      ornamentType: 'svg',
      ornamentSvgKey: 'floralFlourish',
      decorativeBorder: true,
    }
  },
  {
    id: 'fairy-tale',
    name: 'Fairy Tale',
    description: 'Whimsical curves, playful letter shapes, and starry dividers for folklore.',
    category: 'Whimsical',
    bodyFont: "'Alice', serif",
    headingFont: "'Alice', serif",
    fontSize: '15.5px',
    lineHeight: '1.5',
    paragraphSpacing: '0',
    indentation: '1.6em',
    dividerSymbol: '✦ ✵ ✦',
    chapterSpacing: '65px',
    firstParagraphStyle: 'uppercase',
    headerStyle: 'minimal',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.75em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '2em',
      titleWeight: 500,
      titleLetterSpacing: '0.5px',
      topMargin: '22%',
      gapBetweenNumberAndTitle: '8px',
      gapBetweenTitleAndOrnament: '16px',
      gapBetweenOrnamentAndBody: '26px',
      ornamentType: 'svg',
      ornamentSvgKey: 'starBurst',
      decorativeBorder: false,
    }
  },
  {
    id: 'nature',
    name: 'Nature',
    description: 'Organic leaf dividers, natural color tones, and breathing layout.',
    category: 'Nature',
    bodyFont: "'Spectral', serif",
    headingFont: "'Cormorant Garamond', serif",
    fontSize: '15px',
    lineHeight: '1.6',
    paragraphSpacing: '0',
    indentation: '1.5em',
    dividerSymbol: '🍃',
    chapterSpacing: '55px',
    firstParagraphStyle: 'bold',
    headerStyle: 'classic',
    dropCaps: false,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.7em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '2em',
      titleWeight: 400,
      titleLetterSpacing: '0.5px',
      topMargin: '20%',
      gapBetweenNumberAndTitle: '8px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '24px',
      ornamentType: 'svg',
      ornamentSvgKey: 'leafNature',
      decorativeBorder: false,
    }
  },
  {
    id: 'botanical',
    name: 'Botanical',
    description: 'Soft floral design, elegant serif structure, and gentle paragraph flow.',
    category: 'Nature',
    bodyFont: "'Lora', serif",
    headingFont: "'Rochester', cursive",
    fontSize: '15px',
    lineHeight: '1.55',
    paragraphSpacing: '0',
    indentation: '1.5em',
    dividerSymbol: '❀ ☘ ❀',
    chapterSpacing: '50px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.7em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '2.2em',
      titleWeight: 400,
      titleLetterSpacing: '0px',
      topMargin: '20%',
      gapBetweenNumberAndTitle: '6px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '22px',
      ornamentType: 'svg',
      ornamentSvgKey: 'roseRomance',
      decorativeBorder: false,
    }
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Flowing wavy ornaments and breezy text layouts for seaside journals.',
    category: 'Nature',
    bodyFont: "'Lora', serif",
    headingFont: "'Cormorant Garamond', serif",
    fontSize: '15px',
    lineHeight: '1.6',
    paragraphSpacing: '0',
    indentation: '1.4em',
    dividerSymbol: '≋ ≋ ≋',
    chapterSpacing: '45px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: false,
    justify: true,
    dividerStyle: 'line',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.7em',
      numberLetterSpacing: '3px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '2em',
      titleWeight: 400,
      titleLetterSpacing: '0.5px',
      topMargin: '18%',
      gapBetweenNumberAndTitle: '8px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '22px',
      ornamentType: 'svg',
      ornamentSvgKey: 'oceanWave',
      decorativeBorder: false,
    }
  },
  {
    id: 'celestial',
    name: 'Celestial',
    description: 'Star and moon divider elements and ethereal serif title styling.',
    category: 'Whimsical',
    bodyFont: "'Spectral', serif",
    headingFont: "'Cinzel', serif",
    fontSize: '15px',
    lineHeight: '1.5',
    paragraphSpacing: '0',
    indentation: '1.6em',
    dividerSymbol: '☽ ✵ ☾',
    chapterSpacing: '65px',
    firstParagraphStyle: 'small-caps',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.75em',
      numberLetterSpacing: '4px',
      numberWeight: 400,
      numberVariant: 'all-small-caps',
      titleSize: '1.9em',
      titleWeight: 500,
      titleLetterSpacing: '1.5px',
      topMargin: '24%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '16px',
      gapBetweenOrnamentAndBody: '28px',
      ornamentType: 'svg',
      ornamentSvgKey: 'celestialStars',
      decorativeBorder: false,
    }
  },
  {
    id: 'medieval',
    name: 'Medieval',
    description: 'Gothic and calligraphic influence with heavy headers and traditional layout.',
    category: 'Fantasy',
    bodyFont: "'IM Fell English', serif",
    headingFont: "'Cinzel', serif",
    fontSize: '16px',
    lineHeight: '1.45',
    paragraphSpacing: '0',
    indentation: '1.8em',
    dividerSymbol: '✥ ✣ ✥',
    chapterSpacing: '80px',
    firstParagraphStyle: 'uppercase',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.85em',
      numberLetterSpacing: '5px',
      numberWeight: 700,
      numberVariant: 'normal',
      titleSize: '2em',
      titleWeight: 700,
      titleLetterSpacing: '2px',
      topMargin: '26%',
      gapBetweenNumberAndTitle: '12px',
      gapBetweenTitleAndOrnament: '18px',
      gapBetweenOrnamentAndBody: '30px',
      ornamentType: 'svg',
      ornamentSvgKey: 'celticKnot',
      decorativeBorder: true,
    }
  },
  {
    id: 'art-deco',
    name: 'Art Deco',
    description: 'Geometric layouts, bold title headers, and clean linear ornaments.',
    category: 'Contemporary',
    bodyFont: "'Montserrat', sans-serif",
    headingFont: "'Cinzel', serif",
    fontSize: '13.5px',
    lineHeight: '1.65',
    paragraphSpacing: '6px',
    indentation: '0',
    dividerSymbol: '━━━━',
    chapterSpacing: '50px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: false,
    justify: true,
    dividerStyle: 'line',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.8em',
      numberLetterSpacing: '6px',
      numberWeight: 400,
      numberVariant: 'normal',
      titleSize: '2em',
      titleWeight: 700,
      titleLetterSpacing: '3px',
      topMargin: '20%',
      gapBetweenNumberAndTitle: '8px',
      gapBetweenTitleAndOrnament: '14px',
      gapBetweenOrnamentAndBody: '24px',
      ornamentType: 'svg',
      ornamentSvgKey: 'artDecoGeometric',
      decorativeBorder: true,
    }
  },
  {
    id: 'vintage',
    name: 'Vintage',
    description: 'Classic typewriter style layouts and vintage print ornaments.',
    category: 'Contemporary',
    bodyFont: "'Special Elite', cursive",
    headingFont: "'Special Elite', cursive",
    fontSize: '14px',
    lineHeight: '1.5',
    paragraphSpacing: '10px',
    indentation: '0',
    dividerSymbol: '◆ ◇ ◆',
    chapterSpacing: '55px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: false,
    justify: false,
    dividerStyle: 'dots',
    chapterOpening: {
      layout: 'left-aligned',
      numberSize: '0.85em',
      numberLetterSpacing: '2px',
      numberWeight: 400,
      numberVariant: 'normal',
      titleSize: '1.8em',
      titleWeight: 400,
      titleLetterSpacing: '1px',
      topMargin: '20%',
      gapBetweenNumberAndTitle: '6px',
      gapBetweenTitleAndOrnament: '12px',
      gapBetweenOrnamentAndBody: '22px',
      ornamentType: 'svg',
      ornamentSvgKey: 'vintageTypewriter',
      decorativeBorder: false,
    }
  },
  {
    id: 'sci-fi',
    name: 'Sci-Fi',
    description: 'Monospace elements, clean cyber dividers, and layout structures.',
    category: 'Contemporary',
    bodyFont: "'Montserrat', sans-serif",
    headingFont: "'Courier Prime', monospace",
    fontSize: '13px',
    lineHeight: '1.6',
    paragraphSpacing: '8px',
    indentation: '0',
    dividerSymbol: '[ - - ]',
    chapterSpacing: '40px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: false,
    justify: false,
    dividerStyle: 'line',
    chapterOpening: {
      layout: 'left-aligned',
      numberSize: '0.75em',
      numberLetterSpacing: '5px',
      numberWeight: 700,
      numberVariant: 'normal',
      titleSize: '1.8em',
      titleWeight: 400,
      titleLetterSpacing: '2px',
      topMargin: '16%',
      gapBetweenNumberAndTitle: '4px',
      gapBetweenTitleAndOrnament: '12px',
      gapBetweenOrnamentAndBody: '20px',
      ornamentType: 'svg',
      ornamentSvgKey: 'thinRule',
      decorativeBorder: false,
    }
  },
  {
    id: 'mystery',
    name: 'Mystery',
    description: 'Tense typography, typewriter hints, and magnifying glass/key dividers.',
    category: 'Dark',
    bodyFont: "'Special Elite', cursive",
    headingFont: "'Spectral', serif",
    fontSize: '14.2px',
    lineHeight: '1.5',
    paragraphSpacing: '8px',
    indentation: '0',
    dividerSymbol: '🗝',
    chapterSpacing: '60px',
    firstParagraphStyle: 'bold',
    headerStyle: 'classic',
    dropCaps: false,
    justify: false,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.8em',
      numberLetterSpacing: '4px',
      numberWeight: 600,
      numberVariant: 'normal',
      titleSize: '1.9em',
      titleWeight: 600,
      titleLetterSpacing: '1px',
      topMargin: '22%',
      gapBetweenNumberAndTitle: '10px',
      gapBetweenTitleAndOrnament: '16px',
      gapBetweenOrnamentAndBody: '24px',
      ornamentType: 'svg',
      ornamentSvgKey: 'keyMystery',
      decorativeBorder: false,
    }
  },
  {
    id: 'thriller',
    name: 'Thriller',
    description: 'Sharp modern sans-serifs, high contrasts, and rapid-flowing spacing.',
    category: 'Contemporary',
    bodyFont: "'Inter', sans-serif",
    headingFont: "'Montserrat', sans-serif",
    fontSize: '14px',
    lineHeight: '1.55',
    paragraphSpacing: '6px',
    indentation: '0',
    dividerSymbol: '✦',
    chapterSpacing: '40px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: false,
    justify: false,
    dividerStyle: 'line',
    chapterOpening: {
      layout: 'left-aligned',
      numberSize: '0.7em',
      numberLetterSpacing: '5px',
      numberWeight: 700,
      numberVariant: 'normal',
      titleSize: '2.4em',
      titleWeight: 800,
      titleLetterSpacing: '0px',
      topMargin: '16%',
      gapBetweenNumberAndTitle: '4px',
      gapBetweenTitleAndOrnament: '10px',
      gapBetweenOrnamentAndBody: '20px',
      ornamentType: 'svg',
      ornamentSvgKey: 'thinRule',
      decorativeBorder: false,
    }
  },
  {
    id: 'horror',
    name: 'Horror',
    description: 'Gothic and spooky horror theme, dense structures, and creepy bat icons.',
    category: 'Dark',
    bodyFont: "'IM Fell English', serif",
    headingFont: "'Creepster', display",
    fontSize: '16px',
    lineHeight: '1.45',
    paragraphSpacing: '0',
    indentation: '1.75em',
    dividerSymbol: '☠ 🕷 ☠',
    chapterSpacing: '80px',
    firstParagraphStyle: 'uppercase',
    headerStyle: 'classic',
    dropCaps: true,
    justify: true,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.8em',
      numberLetterSpacing: '4px',
      numberWeight: 400,
      numberVariant: 'normal',
      titleSize: '2.2em',
      titleWeight: 400,
      titleLetterSpacing: '2px',
      topMargin: '26%',
      gapBetweenNumberAndTitle: '12px',
      gapBetweenTitleAndOrnament: '18px',
      gapBetweenOrnamentAndBody: '28px',
      ornamentType: 'svg',
      ornamentSvgKey: 'skullHorror',
      decorativeBorder: true,
    }
  },
  {
    id: 'childrens-storybook',
    name: "Children's Storybook",
    description: 'Friendly, rounded curves, high line spacing, and whimsical balloons.',
    category: 'Whimsical',
    bodyFont: "'Quicksand', sans-serif",
    headingFont: "'Quicksand', sans-serif",
    fontSize: '16px',
    lineHeight: '1.7',
    paragraphSpacing: '12px',
    indentation: '0',
    dividerSymbol: '★ 🎈 ★',
    chapterSpacing: '50px',
    firstParagraphStyle: 'bold',
    headerStyle: 'minimal',
    dropCaps: true,
    justify: false,
    dividerStyle: 'ornament',
    chapterOpening: {
      layout: 'centered',
      numberSize: '0.8em',
      numberLetterSpacing: '2px',
      numberWeight: 600,
      numberVariant: 'normal',
      titleSize: '2.2em',
      titleWeight: 700,
      titleLetterSpacing: '0px',
      topMargin: '18%',
      gapBetweenNumberAndTitle: '6px',
      gapBetweenTitleAndOrnament: '12px',
      gapBetweenOrnamentAndBody: '20px',
      ornamentType: 'svg',
      ornamentSvgKey: 'starBurst',
      decorativeBorder: false,
    }
  }
];
